services:
  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:2.19.0
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - DISABLE_SECURITY_PLUGIN=true
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  opensearch-dashboard:
    container_name: opensearch-dashboard
    image: opensearchproject/opensearch-dashboards:2.14.0
    ports:
      - "5601:5601"
    depends_on:
      opensearch:
        condition: service_healthy
    environment:
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
      - OPENSEARCH_HOSTS=http://opensearch:9200
    entrypoint: 
      - sh 
      - -c 
      - "sleep 60 && ./opensearch-dashboards-docker-entrypoint.sh"

volumes:
  opensearch-data:
    driver: local
